### ISSUE TITLE
May I ask why you need the @babel/runtime package in your dependencies?

### ISSUE THREAD

**Issue by mikeconley12** [jaydenseric/apollo-upload-client#254] opened 2021-04-06 15:54 UTC
Please see your `package.json` file https://github.com/jaydenseric/apollo-upload-client/blob/6dec8edc2bb1c97514e1577b84530922a40608bc/package.json#L52 
Is it something that can be easily removed or moved to the `devDependencies` section?

**Comment by jaydenseric** [comment] 2021-04-08 00:00
It belongs where it is, in `dependencies`, because it is used by the published code:

https://unpkg.com/browse/apollo-upload-client@14.1.3/public/createUploadLink.js

With a simple Babel setup, the transpiled code will have little babel helper functions injected in it. The problem is, that those helpers are duplicated again and again in your bundled code (app code, as well as across multiple packages in `node_modules`) instead of being defined once as a module. So, it's a good idea to setup the Babel runtime transformation to swap all those injected helpers for helpers imported from a single package:

https://github.com/jaydenseric/apollo-upload-client/blob/6dec8edc2bb1c97514e1577b84530922a40608bc/src/.babelrc.json#L3

It's annoying that transpiled code uses helpers at all, and I used to do all sorts of tricks to avoid or optimize/substitute them. The ultimate trick is to not use Babel at all, and to just write production ready source code in the first place, which is what I’m moving to over time for all my packages. This is easier to do now than before because we don't have to support IE11 or old Node.js anymore, so we can finally use fairly modern syntax. When this package drops IE11 support (soon; IE11 is EOL this year), I'll drop babel and also the `@babel/runtime` dependency.

**Closed by jaydenseric** 2021-04-08 00:00 UTC
Labels: question
