### ISSUE TITLE
Error adding authorization header  

### ISSUE THREAD

**Issue by jaimepater** [jaydenseric/apollo-upload-client#248] opened 2021-03-01 00:34 UTC
I am adding an authorization header

```
import { ApolloLink, from } from '@apollo/client';
import { createUploadLink } from 'apollo-upload-client';
import { setContext } from '@apollo/client/link/context';
import { API_URL_ENV } from '../../../constants';
import { errorLink } from './link-error';

const uploadLink = (createUploadLink({
  uri: API_URL_ENV,
}) as unknown) as ApolloLink;

const token =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiVXN1YXJpbyIsImlkIjoiNjAwNGUzY2UyNGU0Yjc4MmZkNjViYTM0IiwiaWF0IjoxNjE0NTU3OTcxLCJleHAiOjE2MTQ1NTg1NzF9.MW_hSvNbvvWylHrCrdggdbN5c5RY9Q1kf8QOG4x5FlE';

const auth = setContext((_, { headers }) => {
  return {
    headers: {
      ...headers,
      authorization: `Bearer ${token}`,
    },
  };
});

export const links = from([errorLink, auth, uploadLink]); 
```
When I try to upload a file, I am getting this error
```
{
  "errors": [
    {
      "message": "File missing in the request.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "addProfilePicture"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "message": "File missing in the request.",
          "stacktrace": [
            "BadRequestError: File missing in the request.",
            "    at Busboy.<anonymous> (/Users/jpaternina/Documents/Personal/CM/cm-appointments-bed/node_modules/graphql-upload/lib/processRequest.js:305:37)",
            "    at Object.onceWrapper (events.js:312:28)",
            "    at Busboy.emit (events.js:228:7)",
            "    at Busboy.EventEmitter.emit (domain.js:475:20)",
            "    at Busboy.emit (/Users/jpaternina/Documents/Personal/CM/cm-appointments-bed/node_modules/busboy/lib/main.js:37:33)",
            "    at /Users/jpaternina/Documents/Personal/CM/cm-appointments-bed/node_modules/busboy/lib/types/multipart.js:52:13",
            "    at processTicksAndRejections (internal/process/task_queues.js:76:11)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

the other queries that does not upload a file , works perfectly; in addition I remove the `aut`  middleware and the file object is in the query 

Someone knows what is happening ?

**Comment by jaydenseric** [comment] 2021-03-01 00:48
You're using an out of date `graphql-upload` installation on the server. It's probably not the cause of your problems, but you really need to fix that! It would be interesting to see what the error message is with that updated.

Please check the GraphQL request body is a valid [GraphQL multipart request](https://github.com/jaydenseric/graphql-multipart-request-spec) using the Chrome network inspector; that will help you see if the problem is on the client, or server.

**Comment by jaimepater** [comment] 2021-03-01 02:34
I just update it 
 And this is the new error message 
 
```
{
  "errors": [
    {
      "message": "Variable \"$file\" got invalid value {}; Upload value invalid.",
      "locations": [
        {
          "line": 1,
          "column": 50
        }
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "GraphQLError: Variable \"$file\" got invalid value {}; Upload value invalid.",
            "    at /Users/jpaternina/Documents/Personal/CM/cm-appointments-bed/node_modules/graphql/execution/values.js:116:15",
            "    at coerceInputValueImpl (/Users/jpaternina/Documents/Personal/CM/cm-appointments-bed/node_modules/graphql/utilities/coerceInputValue.js:132:9)",
            "    at coerceInputValueImpl (/Users/jpaternina/Documents/Personal/CM/cm-appointments-bed/node_modules/graphql/utilities/coerceInputValue.js:56:14)",
            "    at coerceInputValue (/Users/jpaternina/Documents/Personal/CM/cm-appointments-bed/node_modules/graphql/utilities/coerceInputValue.js:39:10)",
            "    at _loop (/Users/jpaternina/Documents/Personal/CM/cm-appointments-bed/node_modules/graphql/execution/values.js:109:69)",
            "    at coerceVariableValues (/Users/jpaternina/Documents/Personal/CM/cm-appointments-bed/node_modules/graphql/execution/values.js:121:16)",
            "    at getVariableValues (/Users/jpaternina/Documents/Personal/CM/cm-appointments-bed/node_modules/graphql/execution/values.js:50:19)",
            "    at buildExecutionContext (/Users/jpaternina/Documents/Personal/CM/cm-appointments-bed/node_modules/graphql/execution/execute.js:190:61)",
            "    at executeImpl (/Users/jpaternina/Documents/Personal/CM/cm-appointments-bed/node_modules/graphql/execution/execute.js:87:20)",
            "    at Object.execute (/Users/jpaternina/Documents/Personal/CM/cm-appointments-bed/node_modules/graphql/execution/execute.js:62:35)",
            "    at /Users/jpaternina/Documents/Personal/CM/cm-appointments-bed/node_modules/apollo-server-core/src/requestPipeline.ts:479:22",
            "    at Generator.next (<anonymous>)",
            "    at /Users/jpaternina/Documents/Personal/CM/cm-appointments-bed/node_modules/apollo-server-core/dist/requestPipeline.js:8:71",
            "    at new Promise (<anonymous>)",
            "    at __awaiter (/Users/jpaternina/Documents/Personal/CM/cm-appointments-bed/node_modules/apollo-server-core/dist/requestPipeline.js:4:12)",
            "    at execute (/Users/jpaternina/Documents/Personal/CM/cm-appointments-bed/node_modules/apollo-server-core/dist/requestPipeline.js:220:20)",
            "    at Object.<anonymous> (/Users/jpaternina/Documents/Personal/CM/cm-appointments-bed/node_modules/apollo-server-core/src/requestPipeline.ts:366:30)",
            "    at Generator.next (<anonymous>)",
            "    at fulfilled (/Users/jpaternina/Documents/Personal/CM/cm-appointments-bed/node_modules/apollo-server-core/dist/requestPipeline.js:5:58)",
            "    at processTicksAndRejections (internal/process/task_queues.js:94:5)"
          ]
        }
      }
    }
  ]
}
```
Reviewing my request I realized that the file is null 

```
  ------WebKitFormBoundaryDYcv1n3UorpgG4Zu
Content-Disposition: form-data; name="operations"

{"operationName":"changeProfilePicture","variables":{"id":{"id":"6004e3ce24e4b782fd65ba34"},"file":null},"query":"mutation changeProfilePicture($id: UserIdInput!, $file: Upload!) {\n  addProfilePicture(id: $id, file: $file) {\n    id\n    profilePicture\n    __typename\n  }\n}\n"}
------WebKitFormBoundaryDYcv1n3UorpgG4Zu
Content-Disposition: form-data; name="map"

{"1":["variables.file"]}
------WebKitFormBoundaryDYcv1n3UorpgG4Zu
Content-Disposition: form-data; name="1"

[object Object]
------WebKitFormBoundaryDYcv1n3UorpgG4Zu--
```
 
this is the back-end logs 

```
Variables {
  id: { id: '6004e3ce24e4b782fd65ba34' },
  file: Promise {
    <rejected> BadRequestError: File missing in the request.
        at Busboy.<anonymous> (/Users/jpaternina/Documents/Personal/CM/cm-appointments-bed/node_modules/apollo-server-core/node_modules/graphql-upload/lib/processRequest.js:305:37)
        at Object.onceWrapper (events.js:312:28)
        at Busboy.emit (events.js:228:7)
        at Busboy.EventEmitter.emit (domain.js:475:20)
        at Busboy.emit (/Users/jpaternina/Documents/Personal/CM/cm-appointments-bed/node_modules/busboy/lib/main.js:37:33)
        at /Users/jpaternina/Documents/Personal/CM/cm-appointments-bed/node_modules/busboy/lib/types/multipart.js:52:13
        at processTicksAndRejections (internal/process/task_queues.js:76:11) {
      [stack]: 'BadRequestError: File missing in the request.\n' +
        '    at Busboy.<anonymous> (/Users/jpaternina/Documents/Personal/CM/cm-appointments-bed/node_modules/apollo-server-core/node_modules/graphql-upload/lib/processRequest.js:305:37)\n' +
        '    at Object.onceWrapper (events.js:312:28)\n' +
        '    at Busboy.emit (events.js:228:7)\n' +
        '    at Busboy.EventEmitter.emit (domain.js:475:20)\n' +
        '    at Busboy.emit (/Users/jpaternina/Documents/Personal/CM/cm-appointments-bed/node_modules/busboy/lib/main.js:37:33)\n' +
        '    at /Users/jpaternina/Documents/Personal/CM/cm-appointments-bed/node_modules/busboy/lib/types/multipart.js:52:13\n' +
        '    at processTicksAndRejections (internal/process/task_queues.js:76:11)',
      message: 'File missing in the request.',
      [name]: 'BadRequestError'
    }
  }
} 

```

**Comment by jaydenseric** [comment] 2021-03-01 02:38
Make sure your backend is using only one version of `graphql-upload` for everything; e.g. it will cause problems if the `Upload` scalar ([`GraphQLUpload`](https://github.com/jaydenseric/graphql-upload#class-graphqlupload)) comes from a new version, and the upload middleware comes from an old version.

**Comment by jaydenseric** [comment] 2021-03-01 02:49
> Reviewing my request I realized that the file is null

That is how it is meant to work. What is wrong though, is that the file contents being sent in the multipart form field `1` is `[object Object]`; it should be a big blob of binary data that chrome normally hides when inspecting. This means that the original problem is on the client; the value is being identified as a file, but it's not being added correctly as a file field to the `FormData` instance used as the `fetch` request body.

Investigate exactly what the value is that you are using in variables, is it a `File` instance? What is your `FormData` global, does it accept the `File` instance for it's `.append()` method to create a file field as per web standards? Maybe they are polyfilled incorrectly in your environment. I don't know why your auth link setup would cause problems though, if it was working before.

I can't really debug complicated issues in your app code; so I'm going to close this issue here. If you manage to figure out the root cause relates to a specific, reproducible `apollo-upload-client` bug we can reopen :)

**Closed by jaydenseric** 2021-03-01 02:49 UTC

**Comment by cavator** [comment] 2022-04-08 05:37
i did this, but i always get unauthorized
![image](https://user-images.githubusercontent.com/14593967/162371375-e7c3ef1a-1e0b-4a33-bb7f-f2f0edf4259a.png)
