### ISSUE TITLE
backend get file nothing when ReactNativeFile with video with [Upload] type

### ISSUE THREAD

**Issue by Parkjunwu** [jaydenseric/apollo-upload-client#301] opened 2022-12-14 00:12 UTC
Hello!

I use this library very well, but when upload video file with other files return nothing on backend.

mutation type
fileArr:[Upload!]!,

Case 1 : 
When I send upload data on react-native app by ReactNativeFile like

[
  {
    "uri": "file:///my-file-path1.jpg",
    "name": "0.jpg",
    "type": "image/jpeg"
  },
  {
    "uri": "file:///my-file-path2.jpg",
    "name": "1.jpg",
    "type": "image/jpeg"
  },
  {
    "uri": "my-file-path3.jpg",
    "name": "2.jpg",
    "type": "image/jpeg"
  },
  {
    "uri": "my-file-path4.mp4",
    "name": "3.mp4",
    "type": "video/mp4"
  },
  {
    "uri": "my-file-path5.jpg",
    "name": "4.jpg",
    "type": "image/jpeg"
  }
]

then backend get data like

[
  {
    "promise": {},
    "file": {
      "filename": "0.jpg",
      "mimetype": "image/jpeg",
      "encoding": "7bit"
    }
  },
  {
    "promise": {},
    "file": {
      "filename": "1.jpg",
      "mimetype": "image/jpeg",
      "encoding": "7bit"
    }
  },
  {
    "promise": {}
  },
  {
    "promise": {}
  },
  {
    "promise": {}
  }
]

Case 2 : 

app sending data
[
  {
    "uri": "my-file-path0.mp4",
    "name": "0.mp4",
    "type": "video/mp4"
  },
  {
    "uri": "my-file-path1.mp4",
    "name": "1.mp4",
    "type": "video/mp4"
  }
]

then backend get data

[
  {
    "promise": {},
    "file": {
      "filename": "0.mp4",
      "mimetype": "video/mp4",
      "encoding": "7bit"
    }
  },
  {
    "promise": {}
  }
]

I think this is backend problem when upload video with other files, because upload only one video file or upload only many image files work well.

But sometimes uploading video with other files works with no problem, so I'm not convinced.

Thank you!

backend
"graphql": "^16.6.0",
"graphql-upload": "^15.0.2",

app
"graphql": "^16.6.0",
"apollo-upload-client": "^17.0.0",

**Comment by jaydenseric** [comment] 2023-04-04 22:56
Can you please format and syntax highlight example code when submitting issues on GitHub. I'm not sure your example code is correct, because for the request examples only some of the `uri` start with `file://`.

Firstly, try making the GraphQL multipart requests that upload videos with cURL or a GraphQL client like [Altair](https://altairgraphql.dev) that has GUI for file uploads. This will eliminate the possibility that React Native is doing funny things with the requests on the client side. In the past it has had very strange bugs (not the fault of `apollo-upload-client`) like multipart requests failing just because the network inspector is open when you make a request.

Another thing to consider is that the problem might be large file size, not that some files are videos and others images. Perhaps bigger video uploads cause your nginx or Apache server max request size to be exceeded.

Also consider this sort of thing: https://github.com/jaydenseric/graphql-upload/issues/352#issuecomment-1484086483 .

Closing because in my experience issues like this are almost always specific to the project and not this library, and it's hard for me to investigate from afar. If you are able to isolate a specific bug in my code here with minimal reproduction steps we can reopen.

**Closed by jaydenseric** 2023-04-04 22:56 UTC
