### ISSUE TITLE
File larger than 1MB gets cut off and fails to fetch.

### ISSUE THREAD

**Issue by bgsahagun** [jaydenseric/apollo-upload-client#309] opened 2023-05-23 17:26 UTC
This is my server setup:
![image](https://github.com/jaydenseric/apollo-upload-client/assets/31409505/06e00665-7529-4d0b-add6-583644224eb3)

And this is the error I get after uploading a file larger than 1MB
![image](https://github.com/jaydenseric/apollo-upload-client/assets/31409505/c2a13281-6049-4cf9-a392-a49fa9651338)

The request runs halfway through (proof is that it writes the file into the server halfway) but fails to fetch in the middle. Smaller files successfully finishes. Is anyone having the same issue?

**Comment by jaydenseric** [comment] 2023-05-24 00:49
Closing because this is more a question about your particular server infrastructure; almost certainly the issue is not related to `apollo-upload-client`.

Figure out the maximum request size limits for your server, and any proxies or gateways it's behind. If they are exceeded when uploading files, you will get errors from them and not the nice GraphQL error about exceeded file size etc. from `graphql-upload`. 1MB is a nice round number, so it sounds like an arbitrary limit you would expect to see from a serverless deployment or something. If you are using nginx or Apache, check the request limits configured for it.

Certain developer tools for inspecting network traffic etc. have been known to mess with streamed requests, but I think in this case that is a less likely explanation.

**Closed by jaydenseric** 2023-05-24 00:49 UTC
