### ISSUE TITLE
TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.

### ISSUE THREAD

**Issue by Tjerk-Haaye-Henricus** [jaydenseric/apollo-upload-client#275] opened 2021-11-12 16:39 UTC
Hey there :) 

I'm triing to upload files but since an update i cannot upload anymore.

```
TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.
    at createUploadLink.js:208
    at new Subscription (module.js:190)
    at Observable.subscribe (module.js:264)
    at index.js:11
    at new Subscription (module.js:190)
    at Observable.subscribe (module.js:264)
    at Object.complete (Concast.js:57)
    at Concast.start (Concast.js:83)
    at new Concast (Concast.js:75)
    at QueryManager.getObservableFromLink (QueryManager.js:562)`
````

```js
import { ApolloClient, InMemoryCache, from, ApolloLink } from '@apollo/client';
import { onError } from "@apollo/client/link/error";

import { createUploadLink } from 'apollo-upload-client';

const errorLink = onError(({ graphQLErrors, networkError }) => {
  if (graphQLErrors)
    graphQLErrors.map(({ message, locations, path }) =>
      // eslint-disable-next-line no-console
      console.log(
        `[GraphQL error]: Message: ${message}, Location: ${JSON.stringify(locations)}, Path: ${path}`,
      ),
    );
debugger
  // eslint-disable-next-line no-console
  if (networkError) console.log(`[Network error]: ${networkError}`);
});

const link = from([
  errorLink,
  // eslint-disable-next-line @typescript-eslint/ban-ts-comment
  // @ts-ignore
  createUploadLink(),
]);

// Create the client as outlined in the setup guide
const client = new ApolloClient({
  cache: new InMemoryCache(),
  link,
});


export default client;
```

```js
const uploadImage = (mutation: DocumentNode) => async (file: unknown, areas?): Promise<IResource> => {
  try {
    const { data } = await client.mutate({
      mutation,
      variables: {
        file,
        areas,
      },
    });
    return data.uploadImage;
  } catch (error) {
    console.log(error);
  }
}
```

  System:
    OS: macOS 11.6
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 3.0.0 - /usr/local/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Browsers:
    Chrome: 95.0.4638.69
    Firefox: 93.0
    Safari: 15.0
  npmPackages:
    @apollo/client: ^3.4.16 => 3.5.2 
    apollo-upload-client: ^16.0.0 => 16.0.0

**Comment by pipopotamasu** [comment] 2021-11-13 00:17
related with: https://github.com/jaydenseric/apollo-upload-client/issues/273

when https://github.com/jaydenseric/apollo-upload-client/pull/274 is merged, this issue will be fixed.

**Comment by jaydenseric** [comment] 2021-11-13 00:24
@Tjerk-Haaye-Henricus I edited your issue description markdown to correctly format and syntax highlight the code, in future please do this when sharing blocks of code in GitHub issues or comments:

https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting

@pipopotamasu thanks for the clarification; closing as a duplicate of https://github.com/jaydenseric/apollo-upload-client/issues/273 .

**Closed by jaydenseric** 2021-11-13 00:24 UTC

**Comment by Tjerk-Haaye-Henricus** [comment] 2021-11-13 07:13
Thanks a thousand times for that information 😀 I will do that codesegments better the next time :)
