### ISSUE TITLE
Ionic camera

### ISSUE THREAD

**Issue by sersart** [jaydenseric/apollo-upload-client#144] opened 2019-02-05 15:38 UTC
Hi,
can you please show me, how to use upload with Cordova camera images. 
Thanks

**Comment by jaydenseric** [comment] 2019-02-07 04:46
I have no idea; I don't use it.

Closing since this is more of a usage question, and not a bug with `apollo-upload-client`. Feel free to report back here once you work it out though, for the benefit of anyone else wondering the same thing.

**Closed by jaydenseric** 2019-02-07 04:46 UTC
