### ISSUE TITLE
Mutation error

### ISSUE THREAD

**Issue by ryannealmes** [jaydenseric/apollo-upload-client#26] opened 2017-07-26 09:15 UTC
I am trying to get this working without errors. So far I have managed to get a file uploaded using the middleware, but it returns and error and the store is not updated.

The documentation is great and pretty straight forward. I have set everything up. I keep getting the error:

```
Uncaught (in promise) Error: Network error: A state mutation was detected between dispatches, in the path `apollo.mutations.5.variables.uploadInput`. This may cause incorrect behavior.(http://redux.js.org/docs/Troubleshooting.html#never-mutate-reducer-arguments)
```
My container component is below
```
import React from 'react'
import { graphql, gql, compose } from 'react-apollo'
import UploadBankStatement from '../../components/EftFileUploads/UploadBankStatement.jsx';

const createEftFileUpload = gql`mutation createEftFileUpload(
          $bankAccountCode: String!,
          $uploadInput: UploadInput!,
          $uploadedByPersonCode: String!) {
        createEftFileUpload(
          bankAccountCode: $bankAccountCode,
          uploadInput: $uploadInput,
          uploadedByPersonCode: $uploadedByPersonCode) {
        id
      }
  }`;

const mutationConfig = {
  props: ({ mutate }) => ({
    createEftFileUpload: (bankAccountCode, uploadInput, uploadedByPersonCode) => {

      let variables = {
        bankAccountCode,
        uploadInput,
        uploadedByPersonCode
      };

      return mutate({ variables });
    }
  })
};

export default compose(
  graphql(createEftFileUpload, mutationConfig)
)(UploadBankStatement);

```
Below is the component that  executes the mutation
```
import React, { Component, PropTypes } from 'react';
import gql from 'graphql-tag';
import { graphql, compose } from 'react-apollo';
import { Container, Row, Col, Card, CardBlock } from 'reactstrap';
import BankAccountsSelect from '../../containers/BankAccountsSelectContainer.jsx';

class UploadBankStatement extends Component {
  constructor(props) {
    super(props);

    // this.state = {
    //   bankAccountCode: null
    // };

    this.readFile = this.readFile.bind(this);
  }
  proceed = bankAccountCode => {
    this.bankStatementFile.click();
    // this.setState({ bankAccountCode });
  }

  readFile = e => {
    const files = e.target.files;
    console.log(e.target, e.target.validity);

    if (files && files[0]) {
      const file = files[0];
      this.props.createEftFileUpload(
        "1",
        file,
        "1");
    }
  }

  render() {
    console.log(this.props);
    return (
      <div>
        <input
          type="file"
          className="hidden-xl-down"
          ref={input => { this.bankStatementFile = input; }}
          onChange={this.readFile}
          onClick={e => { e.target.value = null }}
        />
        <BankAccountsSelect proceed={this.proceed} />
      </div>
    );
  }
}

UploadBankStatement.propTypes = {
  mutate: PropTypes.func.isRequired
}

export default UploadBankStatement;

```
Here are the redux events being fired ... 
```
APOLLO_QUERY_INIT
APOLLO_QUERY_INIT
APOLLO_QUERY_RESULT
APOLLO_QUERY_RESULT
APOLLO_MUTATION_INIT
APOLLO_MUTATION_ERROR
```
The details of the error
```
type(pin): "APOLLO_MUTATION_ERROR"
▶error(pin)
name(pin): "Invariant Violation"
framesToPop(pin): 1
mutationId(pin): "5"
```

Please can anyone point to how I can solve this.

**Comment by jaydenseric** [comment] 2017-07-26 09:38
I have not experienced this error before, but maybe the `uploadInput` object is being modified or deleted after the mutation has begun?

Not following what the `reader.readAsDataURL(file)` is for.

**Comment by ryannealmes** [comment] 2017-07-26 11:10
Cleaning up the code, managed to get it working, but still have the error.

**Comment by ryannealmes** [comment] 2017-07-26 11:23
@jaydenseric I have updated the issue. Not really sure what else I can provide?

**Comment by jaydenseric** [comment] 2017-07-26 11:35
Does removing the `onClick={e => { e.target.value = null }}` help?

I don't really have any suggestions other than continue to debug.

**Comment by ryannealmes** [comment] 2017-07-26 12:04
@jaydenseric do you have an example application/repo so I can try set it up and compare?

**Comment by jaydenseric** [comment] 2017-07-26 12:06
Yes! Take a look at [jaydenseric/apollo-upload-examples](https://github.com/jaydenseric/apollo-upload-examples).

**Comment by ryannealmes** [comment] 2017-07-26 13:19
I have managed to get your examples running and working thanks.

I have another question, related to trying to figure this out. In your documentation you have the following example.

```
import React from 'react'
import { graphql, gql } from 'react-apollo'

export default graphql(gql`
  mutation updateUserAvatar($userId: String!, $avatar: Upload!) {
    updateUserAvatar(userId: $userId, avatar: $avatar) {
      id
    }
  }
`)(({ userId, mutate }) => {
  const handleChange = ({ target }) => {
    if (target.validity.valid) {
      mutate({
        variables: {
          userId,
          avatar: target.files[0]
        }
      }).then(({ data }) => console.log('Mutation response:', data))
    }
  }

  return (
    <input
      type="file"
      accept={'image/jpeg,image/png'}
      required
      onChange={handleChange}
    />
  )
})
```
Is user_id a prop that is passed into the control? I haven't really created components like this before. I am wanting to change mine to be inline with your examples and see if that has an impact.

**Comment by ryannealmes** [comment] 2017-07-26 13:26
Nm, after playing around I realize it's just a functional component. UserId is just a prop!

**Comment by jaydenseric** [comment] 2017-07-26 13:27
Yes, `$userId` would come from a prop. It's not exactly how I lay out my components in an actual app, but it is as tight as I could make a meaningful example for the readme.

**Comment by ryannealmes** [comment] 2017-07-26 13:55
So I have done some more research and I think I have made a bit of progress. I am using [react-slingshot](https://github.com/coryhouse/react-slingshot), a fairly widely used repo. I have integrated apollo into it and I am using it's redux store.

It configures the store like so

```
import {createStore, compose, applyMiddleware} from 'redux';
import reduxImmutableStateInvariant from 'redux-immutable-state-invariant';
import thunk from 'redux-thunk';
import rootReducer from '../reducers';

function configureStoreProd(apolloClient, initialState) {
  const middlewares = [
    // Add other middleware on this line...
    apolloClient.middleware(),
    // thunk middleware can also accept an extra argument to be passed to each thunk action
    // https://github.com/gaearon/redux-thunk#injecting-a-custom-argument
    thunk,
  ];

  return createStore(
    rootReducer(apolloClient),
    initialState,
    compose(applyMiddleware(...middlewares))
  );
}

function configureStoreDev(apolloClient, initialState) {
  const middlewares = [
    // Add other middleware on this line...
    apolloClient.middleware(),
    // Redux middleware that spits an error on you when you try to mutate your state either inside a dispatch or between dispatches.
    reduxImmutableStateInvariant(),

    // thunk middleware can also accept an extra argument to be passed to each thunk action
    // https://github.com/gaearon/redux-thunk#injecting-a-custom-argument
    thunk,
  ];

  const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || window.__APOLLO_CLIENT__ || compose; // add support for Redux dev tools

  const store = createStore(
    rootReducer(apolloClient),
    initialState,
    composeEnhancers(applyMiddleware(...middlewares))
  );

  if (module.hot) {
    // Enable Webpack hot module replacement for reducers
    module.hot.accept('../reducers', () => {
      const nextReducer = require('../reducers').default; // eslint-disable-line global-require
      store.replaceReducer(nextReducer);
    });
  }

  return store;
}

const configureStore = process.env.NODE_ENV === 'production' ? configureStoreProd : configureStoreDev;

export default configureStore;

```
I have made a few tweaks so that apollo uses the same redux store as react-slingshot. Note that 1 of the middlewares used in the redux store is `redux-immutable-state-invariant'`. This is what is causing the error. Meaning somehow your middleware is mutating the state (I could be wrong). Disabling this middleware which makes sure you aren't mutating the state makes the error disappear. Maybe this is an issue with the apollo-client, but it is pointing to your middleware? I still have to dive a bit more into your code.

**Comment by jaydenseric** [comment] 2017-07-26 13:58
Hmm interesting. When the files are extracted from the request, the original request is modified rather than creating a modified copy. Maybe it relates to that.

**Comment by ryannealmes** [comment] 2017-07-26 14:44
Could you maybe drop the line where it's being modified please.

**Comment by jaydenseric** [comment] 2017-07-26 14:54
No, that's how it works. It extracts files out of the request. Also, it's not certain that is what is causing your problem yet.

To change the approach to clone requests in memory when they can contain megabytes of files needs to be carefully considered. The `extract-files` dependency would need to be re-written.

I am currently building upload functionality into the new official Apollo network packages, so this whole situation is about to change.

**Comment by ryannealmes** [comment] 2017-07-26 15:01
What would your recommendation be? Is there an eta when this will be done? Do you think I should disable `redux-immutable-state-invariant`? I am pretty sure it is not my code causing the problem since all my other mutations are working.

Is there any way you would like me to help you figure this out?

**Comment by ryannealmes** [comment] 2017-07-28 06:23
Cool. I am a bit busy at the moment, this bug has put me back a couple of days. Going to try catch that up first then will come back to this when I am under less pressure.

**Comment by confiks** [comment] 2017-08-27 17:36
I experienced the same problem immediately after including `apollo-upload-client` into my project. Isn't this simply caused by `extract-files` mutating the Apollo state outside of the reducer [here](https://github.com/jaydenseric/extract-files/blob/master/src/index.js#L42)?

I'll try and see if I can make a reproduction case.

**Comment by ryannealmes** [comment] 2017-08-28 11:03
Sorry I have gone silent on this, but I just don't have capacity right now to be doing stuff that isn't critical to my current work. Short term fix for me was to disable `redux-immutable-state-invariant` :/

**Comment by jaydenseric** [comment] 2017-09-07 06:05
It would be great if someone were to test out [`apollo-fetch-upload`](https://www.npmjs.com/package/apollo-fetch-upload) to see if it is affected too.

**Comment by jaydenseric** [comment] 2017-10-31 06:13
Closing this because it was a pretty edge-case issue that is likely not as relevant in Apollo Client v2, which no longer uses Redux. I am about to rewrite this package to use links for v2 compatibility anyway.

If mutating the original request object because problematic in the future, it might be better to raise an issue at [`extract-files`](https://github.com/jaydenseric/extract-files), as that is what actually causes the mutation. When I originally designed the API for that package, in consultation with the Apollo team it was decided it is ok to mutate the object and save the expense of cloning it.

**Closed by jaydenseric** 2017-10-31 06:13 UTC
