### ISSUE TITLE
Upload not working when running on react native android simulator

### ISSUE THREAD

**Issue by PSPanesar** [jaydenseric/apollo-upload-client#109] opened 2018-08-05 14:44 UTC
I've implemented apollo-upload-client and am using the ReactNativeFile format to upload a file from the app. 

When doing this on iOS simulator this works really well without problems. When trying the upload of the image file on android simulator it falls. 

Its really hard to debug this to know what the error is. 

On Android the URI is a content:// uri and i was thinking if this could be the problem as its not a file:// uri?

All the permissions are set properly on the android app and networking to the graphQL server works fine for all other none upload mutations.

I wonder if you could offer any advice with this?

Thank you.

**Comment by jaydenseric** [comment] 2018-08-06 01:02
I don't have any suggestions, sorry; I don't use React Native myself. [Here is the relevant source for `ReactNativeFile`](https://github.com/jaydenseric/extract-files/blob/v3.1.0/src/index.mjs#L82).

**Comment by PSPanesar** [comment] 2018-08-06 19:30
Hi,
Thanks for that. Yes i don't know where to go next with this. If anyone has React Native experience please do offer some help. I think it may be an issue with the uri format on android but i'm not sure. Otherwise maybe a type mismatch somewhere...
Bw

**Comment by jaydenseric** [comment] 2018-09-27 03:36
Closing because there is nothing I can action at the moment and a fair bit of time has passed. If other React Native users can demonstrate a reproduction we can investigate further…

**Closed by jaydenseric** 2018-09-27 03:36 UTC

**Comment by josemiguelo** [comment] 2019-06-16 22:16
I had the same problem too. I was using `https://github.com/react-native-community/react-native-image-picker`. When I picked my image (using ANDROID), I received something like this:
```json
{
  "height": 768,
  "width": 1024,
  "fileName": "IMG-20190616-WA0033.jpg",
  "fileSize": 106478,
  "path": "/storage/emulated/0/Images/IMG-20190616-WA0033.jpg",
  "uri": "content://media/external/images/media/2691",
  "isVertical": true,
  "originalRotation": 0,
  "type": "IMAGE"
}
```
As you can see, there are like 'two paths': path and uri. I used both when trying to upload the image but none worked. When using iOS, I received something like this:
```json
{
  "fileSize": 13727237,
  "longitude": -122.50956666666667,
  "uri": "file:///Users/user/Library/Developer/CoreSimulator/Devices/...../Documents/C47E913A-B2B6-43C3-A2F1-D8D10BEB1727.jpg",
  "fileName": "IMG_0111.HEIC",
  "latitude": 37.76007833333333,
  "origURL": "assets-library://asset/asset.HEIC?id=CC95F08C-88C3-4012-9D6D-64A413D254B3&ext=HEIC",
  "height": 3024,
  "width": 4032,
  "timestamp": "2018-03-30T19:14:19Z",
  "isVertical": false,
  "type": "IMAGE"
}
```
JUST iOS WORKED when tried to upload the image. So, the thing I did, was to modify my ANDROID path in order to get something like:
`uri: file:///storage/emulated/0/Images/IMG-20190616-WA0033.jpg`
It seems  the path need the prefix "file://"

**Comment by tamhv** [comment] 2019-06-20 04:42
@jaydenseric @josemiguelo @PSPanesar  I got the same issue, both android device and emulator
the same code work well on ios simulator and iphone
```
this.props.uploadMutation({
        variables: {
          document: {
            ...,
            file: new ReactNativeFile({
               uri: photo.path,
               type: photo.mime,
               name: photo.filename
            }),
            ...
          }
        }
      })
```
my backend is django and graphene-file-upload
```
class FileUploadGraphQLView(GraphQLView):
    """Handles multipart/form-data content type in django views"""

    def parse_body(self, request):
        """Handle multipart request spec for multipart/form-data"""
        content_type = self.get_content_type(request)
        if content_type == 'multipart/form-data':
            operations = json.loads(request.POST.get('operations', '{}'))
            files_map = json.loads(request.POST.get('map', '{}'))

            print(request.POST)
            print(request.FILES)
            return place_files_in_operations(
                operations,
                files_map,
                request.FILES
            )

        return super(FileUploadGraphQLView, self).parse_body(request)
```
for ios, it just worked very nice
```
//upload from ios simulator, iphone
//print(request.POST)
<QueryDict: {'operations': ['{"operationName":"MyMutation","variables":{"document":{"file":null}},"query":"mutation MyMutation($document: MyDocumentInput!) {\\n  createDocument(document: $document) {\\n    ok\\n    errors {\\n      field\\n      messages\\n      __typename\\n    }\\n    mydocument {\\n      type\\n      created\\n      url\\n      __typename\\n    }\\n    __typename\\n  }\\n}\\n"}'], 'map': ['{"1":["variables.document.file"]}']}>
# print(request.FILES)
<MultiValueDict: {'1': [<InMemoryUploadedFile: IMG_0003.PNG (image/jpeg)>]}>
```

but from android device, emulator, there are some different in `request.POST` and `request.FILES`
```
//print(request.POST)
<QueryDict: {'operations': ['{"operationName":"MyMutation","variables":{"document":{"file":null}},"query":"mutation MyMutation($document: MyDocumentInput!) {\\n  createDocument(document: $document) {\\n    ok\\n    errors {\\n      field\\n      messages\\n      __typename\\n    }\\n    mydocument {\\n      type\\n      created\\n      url\\n      __typename\\n    }\\n    __typename\\n  }\\n}\\n"}'], 'map': ['{"1":["variables.document.file"]}'], '1': ['����\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00��\x02(ICC_PROFILE\x00\x01\x01\x00\x00\x02\x18\x00\x00\x00\x00\x02\x10\x...............#�\x10���y���=��ap��=���P���l�x�x�^5\x19Z\x1al�t�\'N����']}>
//print(request.FILES)
<MultiValueDict: {}>
```
on android, the file isn't in `request.FILES`, it's included in `request.POST`

versions:
"react-native": "0.59.9",
"apollo-upload-client": "^10.0.1"

client:
```
const authLink = setContext(...)
const errorLink = onError(...)
const parseResponse = new ApolloLink(...)
const httpUploadLink = createUploadLink({
  uri: "...."
})
const client = new ApolloClient({
  link: ApolloLink.from([authLink, errorLink, parseResponse, httpUploadLink]),
  cache: new InMemoryCache({...})
  ...
})
```

**Comment by jaydenseric** [comment] 2019-06-20 05:09
Note this tip [mentioned in the readme](https://github.com/jaydenseric/apollo-upload-client#type-reactnativefilesubstitute):

> Be aware that inspecting network requests with Chrome dev tools interferes with the React Native FormData implementation, causing network errors.

It may or may not relate to your issues.

**Comment by tamhv** [comment] 2019-06-20 05:50
@jaydenseric thank you for quick rely, but i got this issue on a release apk, no debug mode, no dev tools at all

**Comment by tamhv** [comment] 2019-06-20 06:08
sorry my bad, `photo.filename` is undefined on android, it cause this problem

**Comment by CruelMoney** [comment] 2019-07-18 08:30
I have a problem that seems related to this issue. 
Both in the android emulator and in release apk's the upload will stall sometimes. I don't  see any errors in logcat, only after a while I get network request failed, and the request has never hit the server. 

I have double checked on the uri, and it seems to be correct - the mutation gets called this as the upload: 

```
 "file": {
    uri: "file:///data/user/0/host.exp.exponent/cache/ExperienceData/%2540chrisdengso%252Fcueup-gigs/ImagePicker/2639581c-9fe4-4754-b124-9b6465675644.png",
    "name": "profile_picture.png",
    "type": "image/png"
  },
```

Not sure how to proceed with the debugging from here..

**Comment by Kottidev** [comment] 2019-07-30 18:48
@jaydenseric Please check your package with release apk , It work well with debug mode but not with release !
![Screenshot_2019-07-30-19-47-25-75](https://user-images.githubusercontent.com/12915009/62156443-eda79480-b302-11e9-8267-0ec25e0ba470.png)

**Comment by elie222** [comment] 2019-08-16 01:22
We faced the same issue on Android.

**Comment by hrmoller** [comment] 2019-10-28 11:24
Ditto the above comments.

Getting `[Error: Network error: Network request failed]` but requests are never reaching the server. Happens in all environments in both simulator and on physical devices. Android only.

**Comment by hrmoller** [comment] 2019-10-28 12:46
I just fixed it in our case:

Our code looks somewhat like this:
```
const file = new ReactNativeFile(selectedImage);
file.name = 'profilepicture.png';
```

Resulting in an object that looks like this:
```
{
  "name": "profilepicture.png",
  "type": undefined,
  "uri": "file:///some/path/pointing/to/the/file/8136a4e3-029c-4e21-8cfe-cbf5f3256907.png",
}
```

Which caused the upload to fail on Android only.
Simply setting `type` to `image/png` (`"type": "image/png"`) seems to fix it. 

However, I'm not really sure if it actually should've been `image`...?

**Comment by gustavopch** [comment] 2019-12-05 19:10
I got it to work after @hrmoller 's suggestion.

I had:
```js
new ReactNativeFile({
  uri: image.uri,
  name: 'picture',
  type: 'image',
})
```
This change did the trick:
```diff
-  type: 'image',
+  type: 'image/*',
```
:smiley:

**Comment by muganwas** [comment] 2020-05-27 15:02
> I had the same problem too. I was using `https://github.com/react-native-community/react-native-image-picker`. When I picked my image (using ANDROID), I received something like this:
> 
> ```json
> {
>   "height": 768,
>   "width": 1024,
>   "fileName": "IMG-20190616-WA0033.jpg",
>   "fileSize": 106478,
>   "path": "/storage/emulated/0/Images/IMG-20190616-WA0033.jpg",
>   "uri": "content://media/external/images/media/2691",
>   "isVertical": true,
>   "originalRotation": 0,
>   "type": "IMAGE"
> }
> ```
> 
> As you can see, there are like 'two paths': path and uri. I used both when trying to upload the image but none worked. When using iOS, I received something like this:
> 
> ```json
> {
>   "fileSize": 13727237,
>   "longitude": -122.50956666666667,
>   "uri": "file:///Users/user/Library/Developer/CoreSimulator/Devices/...../Documents/C47E913A-B2B6-43C3-A2F1-D8D10BEB1727.jpg",
>   "fileName": "IMG_0111.HEIC",
>   "latitude": 37.76007833333333,
>   "origURL": "assets-library://asset/asset.HEIC?id=CC95F08C-88C3-4012-9D6D-64A413D254B3&ext=HEIC",
>   "height": 3024,
>   "width": 4032,
>   "timestamp": "2018-03-30T19:14:19Z",
>   "isVertical": false,
>   "type": "IMAGE"
> }
> ```
> 
> JUST iOS WORKED when tried to upload the image. So, the thing I did, was to modify my ANDROID path in order to get something like:
> `uri: file:///storage/emulated/0/Images/IMG-20190616-WA0033.jpg`
> It seems the path need the prefix "file://"

I'm using react-native-image-crop-picker and the path provided has the file:// prefix but but the upload doesn't work for android yet it works well for iOS with the same exact prefix.

**Comment by kosmicke** [comment] 2020-06-18 05:40
Hey, @josemiguelo, I was having the same issue that you had. 
In iOS everything was working fine and the files were successfully uploaded, meanwhile, in Android, there was just "Network Error"s.

So I noticed that **in Android** is required to inform some info about the file:
<img width="657" alt="Screen Shot 2020-06-18 at 02 37 22" src="https://user-images.githubusercontent.com/32934713/84982238-a558b700-b10c-11ea-8986-322f21093c9f.png">

So when I gave those info to form data ("name", "uri", "type"), the upload started to work fine!

PS: Im using "react-native-image-picker" to pick the files.

**Comment by marquina-abreu** [comment] 2020-10-05 04:56
<img width="296" alt="Captura de Pantalla 2020-10-05 a la(s) 12 51 12 a  m" src="https://user-images.githubusercontent.com/34238806/95041516-e9180200-06a4-11eb-989a-80d57e820f4a.png">

Hi !
on the android platform is not working for me in either production or debug mode.

I commented on line 43 of ReactNativeFlipper.java and added in the android manifest this android:usesCleartextTraffic="true"

and I still can't upload a product with 1 or more images.

in iOS yes.. in android no

this is my code... where the uri comes with 'file://' ... I tried several ways and nothing.

const generateRNFile = (uri, name) => {
  return uri
    ? new ReactNativeFile({
        uri,
        type: 'image',
        name,
      })
    null;
};

Translated with www.DeepL.com/Translator (free version)

**Comment by luco** [comment] 2021-02-06 15:04
@marquina-abreu Have you tried @hrmoller fix? Works for me.

**Comment by sinn1** [comment] 2022-03-03 23:55
> Note this tip [mentioned in the readme](https://github.com/jaydenseric/apollo-upload-client#type-reactnativefilesubstitute):
> 
> > Be aware that inspecting network requests with Chrome dev tools interferes with the React Native FormData implementation, causing network errors.
> 
> It may or may not relate to your issues.

Just wasted 4 hours of my life
