### ISSUE TITLE
Cloud provider requests coming as http instead of https for graphql requests

### ISSUE THREAD

**Issue by mohit1m** [jaydenseric/apollo-upload-client#258] opened 2021-04-29 05:37 UTC
Cloud provider requests coming as http instead of https for graphql requests. Does the library support SSL requests? We are seeing the cloud provider traffic as http:443.We would like to have it as https:443 with apollo upload client library.

**Comment by jaydenseric** [comment] 2021-04-29 05:39
I'm not sure what your problem is exactly, because you can set whatever `uri` you like in the `createUploadLink` options:

https://github.com/jaydenseric/apollo-upload-client#function-createuploadlink

**Comment by jaydenseric** [comment] 2021-04-29 05:46
Closing because this issue is not actionable. @mohit1m feel free to share here what your problem was, and of course if you do end up finding a reproducible bug we can reopen.

**Closed by jaydenseric** 2021-04-29 05:46 UTC
