### ISSUE TITLE
ReactNativeFile

### ISSUE THREAD

**Issue by harleyxx1** [jaydenseric/apollo-upload-client#347] opened 2024-04-10 12:56 UTC
Hello guys, can I have a suggestion on how can I use ReactNativeFile again in my RN project? Mostly of suggested usage of file upload in RN requires ReactNativeFile but it is already removed in the latest version of the repo.

**Comment by jaydenseric** [comment] 2024-04-10 22:22
As per the release notes:

https://github.com/jaydenseric/apollo-upload-client/releases/tag/v18.0.0

https://github.com/jaydenseric/apollo-upload-client/blob/5e6d5c17861fbd9e2d84c8517fc29d5321be4cfc/changelog.md?plain=1#L27

> To migrate, React Native projects that are unable to use the standard globals can manually implement a class `ReactNativeFile` and match it with a custom function `isReactNativeFile` for use with the function `createUploadLink` option `isExtractableFile`.

Closing this issue because it's a usage question and not a bug report or feature request; but others feel free to share code examples or advice here.

**Closed by jaydenseric** 2024-04-10 22:22 UTC

**Comment by harleyxx1** [comment] 2024-04-11 01:15
Hi @jaydenseric thanks for this. I actually got a working solution using FormData. 

For everyones reference here is how I managed to upload file using GraphQL and axios.

const uploadData = async () => {
    //Create FormData;
    var formData = new FormData();

    //Setting query and variables of perations in formdata.
    const query = `mutation($file:Upload){uploadFile(file:{image:$file,userId:35,createdBy:"ley"}){isSuccessful,message,id}}`;
    const variables = {
      file: null,
    };
    const operations = JSON.stringify({ query, variables: { ...variables } });
    formData.append('operations', operations);

    //Setting map to the formdata.
    const map = {
      '0': ['variables.file'],
    };
    formData.append('map', JSON.stringify(map));

    //Setting file to the formdata.
    formData.append('0', data.file);

    //Calling axios to upload the data.
    await axios({
      url: Config.ENDPOINT,
      method: 'POST',
      data: formData,
      headers: {
        'content-type': 'multipart/form-data',
        'GraphQL-Preflight': 1,
      },
    })
      .then((res) => {})
      .catch((_) => {});
  };
  
  I hope you guys found a solution using this method. 
  
  Thank you!

**Comment by sashrika** [comment] 2024-04-22 03:44
https://github.com/jaydenseric/apollo-upload-client/issues/331#issuecomment-2068428496
