### ISSUE TITLE
v9.0 does not work in node.js 8

### ISSUE THREAD

**Issue by koresar** [jaydenseric/apollo-upload-client#117] opened 2018-09-27 05:39 UTC
Here is the error.
```
 error  in ./node_modules/extract-files/lib/index.mjs

Can't reexport the namespace object from non EcmaScript module (only default export is available)
```

But v8.0 works fine in node.js 8.

**Comment by jaydenseric** [comment] 2018-09-27 05:40
Are you running it in `--experimental-modules` mode? Are you bundling your app?

**Comment by koresar** [comment] 2018-09-27 05:42
Bundling through the latest webpack 4 and latest babel 7.

**Comment by jaydenseric** [comment] 2018-09-27 05:45
It works fine with Webpack v4 and Babel v7 via Next.js [in apollo-upload-examples](https://github.com/jaydenseric/apollo-upload-examples/tree/master/app)… are you sure you don't have some custom resolve config or something?

**Comment by koresar** [comment] 2018-09-27 05:48
I have a default vue-cli project. 
* `vue init my-project` - and then select all the options available.
* `vue add apollo`
...

That was the way I created the project.

**Comment by jaydenseric** [comment] 2018-09-27 05:50
Let me know what you find, but so far I can't reproduce anything. CRA, Next.js, etc. often do wierd custom stuff under the hood breaking normal Webpack or Node.js behaviors. If it turns out to be a vue-cli bug, I'll close the issue here.

**Comment by koresar** [comment] 2018-09-27 05:56
I check the dependency tree - the only project which is using `extract-files` package is `apollo-upload-client`. I solved my problem this way: `npm i -S apollo-upload-client@8`
So, I'm fine.

My understanding is following.
* This module bumped up `"extract-files": "^4.0.0"`
* The `.mjs` files of `apollo-upload-client` are being transpiled. However, it does not transpile its dependencies `.mjs` files. See https://unpkg.com/extract-files@4.0.0/lib/

So, my conclusion. This line
https://github.com/jaydenseric/apollo-upload-client/blob/master/src/index.js#L10
tries to load `.mjs` instead of `.js`. I have no idea why.

**Comment by jaydenseric** [comment] 2018-09-27 05:56
After just a quick search of the `vue-cli` repo I found this: https://github.com/vuejs/vue-cli/blob/v3.0.4/packages/%40vue/cli-service/lib/config/base.js#L41

Looks like they are setting custom resolve config without accounting for `.mjs`, which should come first in the resolve order.

**Comment by jaydenseric** [comment] 2018-09-27 05:58
Closing because this is a Webpack config issue in `vue-cli`.

**Closed by jaydenseric** 2018-09-27 05:58 UTC

**Comment by jaydenseric** [comment] 2018-09-27 06:00
Here is an example of what it should look like: https://github.com/zeit/next.js/blob/7.0.1-canary.0/build/webpack.js#L155

**Comment by koresar** [comment] 2018-09-27 07:10
Thanks!

**Comment by ScreamZ** [comment] 2018-10-26 15:02
Nice, thanks for reporting.

**Comment by vvision** [comment] 2018-10-31 16:14
Not related to vue-cli ,but had the following error also with ".mjs" added and version ^9.0.0 :
````
ERROR in ./node_modules/extract-files/lib/index.mjs 1:0-30
Can't reexport the namespace object from non EcmaScript module (only default export is available)
 @ ./node_modules/apollo-upload-client/lib/index.js
````

Had to downgrade to ^8.0.0 to fix it.

**Comment by jaydenseric** [comment] 2018-11-01 00:50
@vvision this package is not using `.mjs` at all, if you are having issues with `extract-files` it is better to file an issue in that repo. But I can tell already, you have a misconfigured bundler that is not following the the current Node.js resolve algorithm.
